spring:
  application:
    name: homework

  flyway:
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:homework;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  sql:
    init:
      platform: h2
      schema-locations: classpath:db/test/init.sql
      data-locations: classpath:db/test/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8990
